pipeline {
    agent any

    environment {
        DOCKER_HOST = 'tcp://localhost:2375'  // Docker Host URI for Docker Desktop on Windows
        DOCKER_TLS_VERIFY = '0'  // Disable TLS verification
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from Git
                git branch: 'main', url: 'https://github.com/sdeschaepmeester/Architest.git'
            }
        }
        stage('Build') {
            steps {
                dir('frontend') {
                    script {
                        def customImage = docker.build('frontend-test', '-f Dockerfile .')
                        customImage.push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        docker.image('frontend-test').run('-p 8081:80')
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline successful!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
